name: Precision Marketing Partners
favicon: null
layout_spectrum: 0.02891954849474132
typography_spectrum: 0.3778754591476172
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9797619658056647
  lightness: 0.0250585051253438
  saturation: 0.009967404883354902
  rhythmicContrast: 0.6576310880482197
purpose: []
